Front 63
NicolasR464/trocup-front pull request #7
Opened 2024-10-26 18:55 UTC by Loroha

- added link with article data and user data
- Modified user type to add "last connected" data

2024-10-28 17:42 UTC, NicolasR464 requested changes

2024-10-28 17:42 UTC, NicolasR464 commented on src/app/articles/[id]/page.tsx
> +import { AvatarFallback } from '@radix-ui/react-avatar'
Tu as un avatar placeholder. Tu peux voir son utilisation dans la page onboarding.

2024-10-28 17:42 UTC, NicolasR464 commented on src/app/articles/[id]/page.tsx
> +                                ''
Au lieu du ternary operator tu peux utiliser le '&&' ici.

2024-10-28 17:42 UTC, NicolasR464 commented on src/utils/apiCalls/user/index.ts
> +export const getUserById = async (
Tu peux faire sans le try catch comme tu as fait pour getArticleById

2024-10-28 17:42 UTC, NicolasR464 commented on src/utils/apiCalls/article/index.ts
> +export const getArticlesById = async (id: string): Promise<Article> => {
Faudrait mettre `articles` au singulier pour être plus explicite.

2024-10-28 17:42 UTC, NicolasR464 commented on src/utils/constants/endpoints.ts
> +    ARTICLES: 'articles/',
C'est bizarre que celui-ci n'est pas le préfixe `api` comme les autres à voir avec le back...plus tard.

2024-10-28 17:42 UTC, NicolasR464 commented on src/utils/functions/index.ts
> +
Tu peux enlever cet espace.

2024-10-28 18:42 UTC, Loroha commented on src/app/articles/[id]/page.tsx
> +import { AvatarFallback } from '@radix-ui/react-avatar'
Je ne le vois pas dans onvoarding ?

2024-10-28 18:44 UTC, Loroha commented on src/utils/constants/endpoints.ts
> +    ARTICLES: 'articles/',
si je mets /api c'est la version avec middleware. sans le /api, articles est accessible par tous.

2024-10-28 18:46 UTC, Loroha commented on src/utils/functions/index.ts
> +
**ok**

2024-10-28 18:47 UTC, Loroha commented on src/utils/apiCalls/article/index.ts
> +export const getArticlesById = async (id: string): Promise<Article> => {
ok

2024-10-28 18:47 UTC, Loroha commented on src/utils/apiCalls/user/index.ts
> +export const getUserById = async (
ok

2024-10-28 18:47 UTC, Loroha commented on src/app/articles/[id]/page.tsx
> +                                ''
ok

2024-10-28 18:58 UTC, NicolasR464 commented on src/app/articles/[id]/page.tsx
> +import { AvatarFallback } from '@radix-ui/react-avatar'
src/components/forms/userRegistration.tsx:233

2024-10-29 09:52 UTC, NicolasR464 approved these changes

2024-10-29 09:52 UTC, merged